name: Build and Deploy Jekyll

on:
  push:
    branches:
      - main  # 你要触发部署的分支（比如 main 分支）
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'  # 这里可以换成你需要的 Ruby 版本

      - name: Install Jekyll and Bundler
        run: gem install jekyll bundler

      - name: Install dependencies
        run: bundle install

      - name: Build the site
        run: JEKYLL_ENV=production bundle exec jekyll build

      - name: Deploy to GitHub Pages
         uses: actions/upload-artifact@v2

          name: site
          path: _site
